// Copyright (C) 2025 kanel
// This file is part of "Pulse"
// For conditions of distribution and use, see copyright notice in LICENSE

#ifdef PULSE_ENABLE_SOFTWARE_BACKEND

#ifndef PULSE_SOFTWARE_ENUMS_H_
#define PULSE_SOFTWARE_ENUMS_H_

typedef enum SoftCommandType
{
	SOFT_COMMAND_NONE = 0,
	SOFT_COMMAND_BLIT_IMAGES,
	SOFT_COMMAND_COPY_BUFFER_TO_BUFFER,
	SOFT_COMMAND_COPY_BUFFER_TO_IMAGE,
	SOFT_COMMAND_COPY_IMAGE_TO_BUFFER,
	SOFT_COMMAND_DISPATCH,
	SOFT_COMMAND_DISPATCH_INDIRECT,

	SOFT_COMMAND_END_ENUM // For internal use only
} SoftCommandType;

#endif // PULSE_SOFTWARE_ENUMS_H_

#endif // PULSE_ENABLE_SOFTWARE_BACKEND
