// Copyright (C) 2024 kanel
// This file is part of "Pulse"
// For conditions of distribution and use, see copyright notice in LICENSE

#ifndef PULSE_ENUMS_H_
#define PULSE_ENUMS_H_

typedef enum PulseCommandListState
{
	PULSE_COMMAND_LIST_STATE_INVALID,
	PULSE_COMMAND_LIST_STATE_EMPTY,
	PULSE_COMMAND_LIST_STATE_RECORDING,
	PULSE_COMMAND_LIST_STATE_READY,
	PULSE_COMMAND_LIST_STATE_SENT
} PulseCommandListState;

typedef enum PulseErrorType
{
	PULSE_ERROR_NONE,

	PULSE_ERROR_DEVICE_LOST,
	PULSE_ERROR_INVALID_HANDLE,
	PULSE_ERROR_INVALID_INTERNAL_POINTER,
	PULSE_ERROR_INITIALIZATION_FAILED,
	PULSE_ERROR_CPU_ALLOCATION_FAILED,
	PULSE_ERROR_DEVICE_ALLOCATION_FAILED,
	PULSE_ERROR_BACKENDS_CANDIDATES_SHADER_FORMAT_MISMATCH,
} PulseErrorType;

typedef enum PulseWarningType
{
	PULSE_WARNING_NONE,
} PulseWarningType;

#endif
