// Copyright (C) 2025 kanel
// This file is part of "Pulse"
// For conditions of distribution and use, see copyright notice in LICENSE

// No header guards

#ifndef PULSE_EGL_FUNCTION
	#error "You must define PULSE_EGL_FUNCTION before including this file"
#endif

#ifndef PULSE_EGL_FUNCTION_EXT
	#error "You must define PULSE_EGL_FUNCTION_EXT before including this file"
#endif

PULSE_EGL_FUNCTION(eglBindAPI, PFNEGLBINDAPIPROC)
PULSE_EGL_FUNCTION(eglChooseConfig, PFNEGLCHOOSECONFIGPROC)
PULSE_EGL_FUNCTION(eglCreateContext, PFNEGLCREATECONTEXTPROC)
PULSE_EGL_FUNCTION(eglCreatePbufferSurface, PFNEGLCREATEPBUFFERSURFACEPROC)
PULSE_EGL_FUNCTION(eglDestroyContext, PFNEGLDESTROYCONTEXTPROC)
PULSE_EGL_FUNCTION(eglDestroySurface, PFNEGLDESTROYSURFACEPROC)
PULSE_EGL_FUNCTION(eglGetConfigAttrib, PFNEGLGETCONFIGATTRIBPROC)
PULSE_EGL_FUNCTION(eglGetDisplay, PFNEGLGETDISPLAYPROC)
PULSE_EGL_FUNCTION(eglGetError, PFNEGLGETERRORPROC)
PULSE_EGL_FUNCTION(eglGetProcAddress, PFNEGLGETPROCADDRESSPROC)
PULSE_EGL_FUNCTION(eglInitialize, PFNEGLINITIALIZEPROC)
PULSE_EGL_FUNCTION(eglMakeCurrent, PFNEGLMAKECURRENTPROC)
PULSE_EGL_FUNCTION(eglQueryString, PFNEGLQUERYSTRINGPROC)
PULSE_EGL_FUNCTION(eglTerminate, PFNEGLTERMINATEPROC)

PULSE_EGL_FUNCTION_EXT(eglQueryDevicesEXT, PFNEGLQUERYDEVICESEXTPROC)
PULSE_EGL_FUNCTION_EXT(eglGetPlatformDisplayEXT, PFNEGLGETPLATFORMDISPLAYEXTPROC)
